# --- User's custom definitions

# ---

MAXCOMPILER_QUOTE   := $(shell printf %q "$(MAXCOMPILERDIR)")

RUNRULE_ARGS        := ../../DOCS/example.tif
RUNRULE_RUNENV      := LD_LIBRARY_PATH="$(MAXELEROSDIR)/lib:$(LD_LIBRARY_PATH)" 
RUNRULE_MAXFILES    := Spdm.max  
RUNRULE_MAXFILES_H  := Spdm.h 
RUNRULE_CFLAGS      := 
RUNRULE_LDFLAGS     := 

TARGET_EXEC         := Spdm
TARGET_LIBRARY      := 


